[package]
authors = ["Zondax GmbH <info@zondax.ch>"]
name = "rustee_ta"
version = "0.1.0"
edition = "2018"
readme = "README.md"

[lib]
name = "rustee_ta"
crate-type = ["staticlib"]

[target.armv7-unknown-linux-gnueabihf.dev-dependencies]
panic-halt = "0.2.0"

[dependencies.rand]
version = "0.7.3"
default-features = false
features = ["getrandom"]

[dependencies.rand_core]
version = "0.5.1"
default-features = false

[dependencies.schnorrkel]
version = "0.9.1"
default-features = false
features = ["u32_backend", "getrandom"]

[dependencies.heapless]
version = "0.5.3"

[dev-dependencies.log]
version = "0.4.8"

[dev-dependencies.simple_logger]
version = "1.6.0"
