[package]
authors = ["Zondax GmbH <info@zondax.ch>"]
name = "rustee_ta"
version = "0.1.0"
edition = "2018"
readme = "README.md"

[lib]
name = "rustee_ta"
crate-type = ["staticlib"]

[target.armv7-unknown-linux-gnueabihf.dev-dependencies]
panic-halt = "0.2.0"
