[package]
name = "ta_app"
version = "0.1.0"
authors = ["neithanmo <neithanmo@gmail.com>"]
edition = "2018"

[dependencies]
optee_common = {package = "optee-common", path = "../optee-common", version = "0.1.0"}
log = "0.4"

